version: "3.9"

services:
  soap-client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - PORT=${PORT}
      - JWT_SEED=${JWT_SEED}
      - SOAP_BASE_URL=${SOAP_BASE_URL}
    ports:
      - "4000:4000"
